import test from "node:test";
import assert from "node:assert/strict";
import {
  validatePinFormat,
  hashPin,
  verifyPinHash,
} from "../src/lib/auth/pin";
import {
  signToken,
  verifySignedToken,
} from "../src/lib/auth/session";
import {
  recordFailedAttempt,
  checkRateLimit,
  resetRateLimit,
  MAX_ATTEMPTS,
} from "../src/lib/auth/rate-limiter";

test("Security Review: Rejects malformed or malicious PIN payloads", () => {
  const maliciousInputs = [
    "123",
    "12345",
    "123a",
    "' OR '1'='1",
    "<script>",
    "admin",
    "00000",
    "-123",
    "12.3",
    " 123",
    "123 ",
  ];

  for (const input of maliciousInputs) {
    assert.equal(
      validatePinFormat(input),
      false,
      `Payload "${input}" should be rejected by validatePinFormat`
    );
  }
});

test("Security Review: Rate limiter enforces lockout after MAX_ATTEMPTS failures", async () => {
  const testIp = "192.168.100.99";

  // Reset before testing
  await resetRateLimit(testIp);

  // First 4 attempts should not lock
  for (let i = 1; i < MAX_ATTEMPTS; i++) {
    const res = await recordFailedAttempt(testIp);
    assert.equal(res.isLockedNow, false, `Attempt ${i} should not trigger lockout`);
    assert.equal(res.attemptsLeft, MAX_ATTEMPTS - i);
  }

  // 5th attempt must trigger lockout
  const finalAttempt = await recordFailedAttempt(testIp);
  assert.equal(finalAttempt.isLockedNow, true, "5th attempt must lock out");
  assert.equal(finalAttempt.attemptsLeft, 0);

  // Check rate limit status
  const status = await checkRateLimit(testIp);
  assert.equal(status.isLocked, true, "IP should be reported as locked");
  assert.ok(status.remainingMinutes && status.remainingMinutes > 0);

  // Clean up
  await resetRateLimit(testIp);
  const statusAfterReset = await checkRateLimit(testIp);
  assert.equal(statusAfterReset.isLocked, false, "IP should be unlocked after reset");
});

test("Security Review: Password hashing is strictly non-reversible and unique per salt", async () => {
  const pin = "7391";
  const hash1 = await hashPin(pin);
  const hash2 = await hashPin(pin);

  // Hashes must be different because of random unique salts generated by Argon2id
  assert.notEqual(hash1, hash2, "Argon2id salts must produce different hashes for same PIN");

  // Both hashes must verify successfully with the correct PIN
  assert.equal(await verifyPinHash(hash1, pin), true);
  assert.equal(await verifyPinHash(hash2, pin), true);

  // Neither hash must match an incorrect PIN
  assert.equal(await verifyPinHash(hash1, "7392"), false);
});

test("Security Review: Session signature prevents forged cookies", async () => {
  const validToken = "myvalidtokendatastring1234567890";
  const signedCookie = await signToken(validToken);

  // Attempt forgery with altered payload
  const forgedPayload = "attacker_session_token_1234567890";
  const forgedCookie = `${forgedPayload}.${signedCookie.split(".")[1]}`;
  const forgedResult = await verifySignedToken(forgedCookie);
  assert.equal(forgedResult, null, "Forged token with copied signature must be rejected");

  // Attempt empty or missing signature
  assert.equal(await verifySignedToken(validToken), null, "Unsigned token must be rejected");
});
